CREATE TABLE prof(
     id INT AUTO_INCREMENT PRIMARY KEY,
     sala VARCHAR(100) NOT NULL,
     descrição VARCHAR(100) NOT NULL,
     nome VARCHAR(100) NOT NULL,
     data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)